#!/usr/bin/env bash
# Regenerates ios/Models/GeneratedAssets.swift from backend gameplay_config.toml,
# maze.json, and the golden sim-parity fixture.
#
# Bakes into Swift:
#   - configHash   — sha256(gameplay_config.toml bytes)
#   - mazeHash     — sha256(maze.json bytes)
#   - gameplayConfigTOML — verbatim TOML (for hash inspection)
#   - gameplayConfigJSON — TOML converted to JSON (iOS parses this via JSONDecoder)
#   - mazeJSON     — verbatim maze.json bytes
#   - simParityFixture — tests/fixtures/sim_parity.json, embedded for SimParityRunner
#
# Re-run after editing gameplay_config.toml, maze.json, or after
# `cargo run --bin generate_golden`.

set -euo pipefail

BACKEND_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
IOS_ROOT="${IOS_ROOT:?set IOS_ROOT to the legacy Swift client checkout}"
OUT="$IOS_ROOT/Models/GeneratedAssets.swift"

CONFIG_PATH="$BACKEND_ROOT/gameplay_config.toml"
MAZE_PATH="$BACKEND_ROOT/maze.json"
FIXTURE_PATH="$BACKEND_ROOT/tests/fixtures/sim_parity.json"

[[ -f "$CONFIG_PATH" ]] || { echo "missing $CONFIG_PATH" >&2; exit 1; }
[[ -f "$MAZE_PATH"   ]] || { echo "missing $MAZE_PATH"   >&2; exit 1; }
if [[ ! -f "$FIXTURE_PATH" ]]; then
  echo "missing $FIXTURE_PATH — run 'cargo run --bin generate_golden' first" >&2
  exit 1
fi

CONFIG_HASH=$(shasum -a 256 "$CONFIG_PATH" | awk '{print $1}')
MAZE_HASH=$(shasum -a 256 "$MAZE_PATH" | awk '{print $1}')

CONFIG_BODY=$(cat "$CONFIG_PATH")
MAZE_BODY=$(cat "$MAZE_PATH")
FIXTURE_BODY=$(cat "$FIXTURE_PATH")

# TOML → JSON for iOS parsing. tomllib is stdlib in Python 3.11+.
CONFIG_JSON=$(python3 -c "
import json, tomllib, sys
with open(sys.argv[1], 'rb') as f:
    data = tomllib.load(f)
print(json.dumps(data, indent=2))
" "$CONFIG_PATH")

cat > "$OUT" <<EOF
// AUTO-GENERATED by scripts/generate_ios_assets.sh — DO NOT EDIT BY HAND.
// Re-run the script after editing gameplay_config.toml, maze.json, or
// after \`cargo run --bin generate_golden\`.

import Foundation

enum GeneratedAssets {
    static let protocolVersion: UInt32 = 2
    static let configHash = "$CONFIG_HASH"
    static let mazeHash = "$MAZE_HASH"

    /// Verbatim bytes of gameplay_config.toml at generation time.
    /// (Kept for hash inspection / debugging.)
    static let gameplayConfigTOML: String = #"""
$CONFIG_BODY
"""#

    /// gameplay_config.toml converted to JSON for iOS JSONDecoder consumption.
    /// The TOML form remains the canonical hash input — JSON here is just a
    /// parsing convenience for the client.
    static let gameplayConfigJSON: String = #"""
$CONFIG_JSON
"""#

    /// Verbatim bytes of maze.json at generation time.
    static let mazeJSON: String = #"""
$MAZE_BODY
"""#

    /// Cross-platform sim-parity fixture. SimParityRunner replays this and
    /// asserts pureStep matches the recorded samples to within 0.001px.
    static let simParityFixture: String = #"""
$FIXTURE_BODY
"""#
}
EOF

echo "Wrote $OUT"
echo "  configHash = $CONFIG_HASH"
echo "  mazeHash   = $MAZE_HASH"
echo "  fixture scenarios: $(python3 -c "import json,sys; print(len(json.load(open(sys.argv[1]))['scenarios']))" "$FIXTURE_PATH")"
