#!/usr/bin/env bash
# Syncs the shared gameplay assets into the Unity client at $UNITY_ROOT (default: a
# sibling `unity/` checkout next to this repo) — the live client, NOT the legacy Swift
# project that generate_ios_assets.sh targets.
#
# The Unity client computes its Hello-handshake config_hash / maze_hash from these
# StreamingAssets bytes (see Assets/Scripts/Game/GameAssets.cs), and the server rejects
# the connection unless they match byte-for-byte. SimParityRunner replays the fixture.
# So all three MUST stay identical to the backend, or the client silently drifts:
#   - gameplay_config.toml  ← backend gameplay_config.toml   (handshake config_hash)
#   - maze.json             ← backend maze.json              (handshake maze_hash)
#   - sim_parity.json       ← backend tests/fixtures/sim_parity.json (parity fixture)
#
# Re-run after editing gameplay_config.toml / maze.json, or after
# `cargo run --bin generate_golden`. The .meta files are left untouched (Unity GUIDs).

set -euo pipefail

BACKEND_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
UNITY_ROOT="${UNITY_ROOT:-$BACKEND_ROOT/../unity}"
STREAMING="$UNITY_ROOT/Assets/StreamingAssets"

CONFIG_SRC="$BACKEND_ROOT/gameplay_config.toml"
MAZE_SRC="$BACKEND_ROOT/maze.json"
FIXTURE_SRC="$BACKEND_ROOT/tests/fixtures/sim_parity.json"

for f in "$CONFIG_SRC" "$MAZE_SRC" "$FIXTURE_SRC"; do
  [[ -f "$f" ]] || { echo "missing source $f" >&2; exit 1; }
done
[[ -d "$STREAMING" ]] || { echo "missing Unity StreamingAssets dir $STREAMING (set UNITY_ROOT?)" >&2; exit 1; }

sha() { shasum -a 256 "$1" | awk '{print $1}'; }
# Pull a top-level string field out of the fixture JSON (python3 is already a dep of
# the sibling generate_ios_assets.sh).
fixture_field() { python3 -c "import json,sys; print(json.load(open(sys.argv[1]))[sys.argv[2]])" "$FIXTURE_SRC" "$1"; }

# GUARD (the Blocker-2 drift class): the fixture embeds the config/maze hashes it was
# recorded under. If those don't match the current source files, the fixture is STALE —
# regenerate it before syncing, else we'd ship samples recorded under a different config.
CONFIG_HASH="$(sha "$CONFIG_SRC")"
MAZE_HASH="$(sha "$MAZE_SRC")"
FIXTURE_CONFIG_HASH="$(fixture_field config_hash)"
FIXTURE_MAZE_HASH="$(fixture_field maze_hash)"

if [[ "$CONFIG_HASH" != "$FIXTURE_CONFIG_HASH" || "$MAZE_HASH" != "$FIXTURE_MAZE_HASH" ]]; then
  echo "ERROR: tests/fixtures/sim_parity.json is STALE — regenerate it before syncing:" >&2
  echo "         cargo run --bin generate_golden" >&2
  echo "  config_hash  source=$CONFIG_HASH  fixture=$FIXTURE_CONFIG_HASH" >&2
  echo "  maze_hash    source=$MAZE_HASH  fixture=$FIXTURE_MAZE_HASH" >&2
  exit 1
fi

cp "$CONFIG_SRC"  "$STREAMING/gameplay_config.toml"
cp "$MAZE_SRC"    "$STREAMING/maze.json"
cp "$FIXTURE_SRC" "$STREAMING/sim_parity.json"

# Snapshot WIRE fixture (protocol v6): the same keyframe+delta as bincode and as JSON.
# The Unity EditMode test decodes both and asserts equality - pinning the C# BincodeDecoder
# to the Rust encoder. Regenerated by `cargo run --bin generate_golden` alongside sim_parity.
for f in snapshot_keyframe.bin snapshot_delta.bin snapshot_frames.json; do
  [[ -f "$BACKEND_ROOT/tests/fixtures/$f" ]] || { echo "missing $f - run cargo run --bin generate_golden" >&2; exit 1; }
  cp "$BACKEND_ROOT/tests/fixtures/$f" "$STREAMING/$f"
done

# Regenerate the client's bootstrap constants FROM the same config (single source of truth):
# the few values the client needs before Welcome (protocol version, map size, tick rate, base
# speeds) are GENERATED into GameConstants.cs rather than hand-synced. Runtime-tunable fairness
# values travel in Welcome instead, so they're not emitted here.
GAME_CONSTANTS="$UNITY_ROOT/Assets/Scripts/Sim/GameConstants.cs"
( cd "$BACKEND_ROOT" && cargo run --quiet --bin generate_constants -- "$GAME_CONSTANTS" )

echo "Synced Unity StreamingAssets ← backend ($STREAMING):"
echo "  gameplay_config.toml  config_hash = $CONFIG_HASH"
echo "  maze.json             maze_hash   = $MAZE_HASH"
echo "  sim_parity.json       scenarios   = $(python3 -c "import json,sys; print(len(json.load(open(sys.argv[1]))['scenarios']))" "$FIXTURE_SRC")"
echo "  GameConstants.cs      generated   ← gameplay_config.toml"
echo "Open the Unity Editor (or let it reimport) so the new bytes are picked up."
